// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mJU3w7LiKHPBKUALsVD2dj
// Component: GPII4fC9bhF
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: kodhyUpj2vfND/component

import { useScreenVariants as useScreenVariantsohuKUq66Y5Rscr } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ohuKUq66y5rscr/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_mavia_sun.module.css"; // plasmic-import: mJU3w7LiKHPBKUALsVD2dj/projectcss
import sty from "./PlasmicBlogPost.module.css"; // plasmic-import: GPII4fC9bhF/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ZNnQiOQA-EMqaf/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: CzXEhqLtaA5P__/icon

export type PlasmicBlogPost__VariantMembers = {};

export type PlasmicBlogPost__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogPost__VariantsArgs;
export const PlasmicBlogPost__VariantProps = new Array<VariantPropType>();

export type PlasmicBlogPost__ArgsType = {};
type ArgPropType = keyof PlasmicBlogPost__ArgsType;
export const PlasmicBlogPost__ArgProps = new Array<ArgPropType>();

export type PlasmicBlogPost__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBlogPostProps {
  className?: string;
}

function PlasmicBlogPost__RenderFunc(props: {
  variants: PlasmicBlogPost__VariantsArgs;
  args: PlasmicBlogPost__ArgsType;
  overrides: PlasmicBlogPost__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsohuKUq66Y5Rscr()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__cJi5A)}>
        <div className={classNames(projectcss.all, sty.freeBox___8PD4F)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__kRyiJ)}
          >
            <div className={classNames(projectcss.all, sty.column__e5O3T)}>
              <div className={classNames(projectcss.all, sty.columns__fq8D)}>
                <div className={classNames(projectcss.all, sty.column___82Yls)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__o0JlH)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/istockphoto1306171737170667Ajpg2.jpeg",
                      fullWidth: 509,
                      fullHeight: 340,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__slOp)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xobga)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__gaXnd
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a748
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__axTfI
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg___6Fqh)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__nxKv)}>
              <div className={classNames(projectcss.all, sty.columns__ksb72)}>
                <div className={classNames(projectcss.all, sty.column___1DwGi)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__cTkOc)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/istockphoto1306171737170667Ajpg2.jpeg",
                      fullWidth: 509,
                      fullHeight: 340,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___4XyiA)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jf0Gs)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__c0Toj
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__sIJz5
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__nx3Gj
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__l1Im7)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__tj8BM)}>
              <div className={classNames(projectcss.all, sty.columns__ymXSs)}>
                <div className={classNames(projectcss.all, sty.column__qv83T)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kb7J)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/fakurianDesignPPTwRTkvXqUnsplashjpg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__kcj5Z)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kdEor)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__uHbf
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__usZx2
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__jVcxw
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__mrmmK)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__kCDiX)}>
              <div className={classNames(projectcss.all, sty.columns__wEpVh)}>
                <div className={classNames(projectcss.all, sty.column__twMli)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__nDzr)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/fakurianDesignLfbhDph3QYUnsplashjpg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1080,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__sy02W)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mrCwc)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__kmmYh
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yg7AG
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames("__wab_instance", sty.button__t5F0)}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__ntLsi)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__gr5VI)}>
              <div className={classNames(projectcss.all, sty.columns___9NxGi)}>
                <div className={classNames(projectcss.all, sty.column__gxe6M)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__lze3A)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/xpsOcAuPlfZxEcUnsplashjpg.jpeg",
                      fullWidth: 640,
                      fullHeight: 360,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__bqn60)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___1ZNj5)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__vqNmL
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hItp
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___8AlEb
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__im19T)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column___6CTjQ)}>
              <div className={classNames(projectcss.all, sty.columns__qbHQ)}>
                <div className={classNames(projectcss.all, sty.column__zTnM6)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dm8Au)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/corinneKutzTMi2R5NfoUnsplashjpg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___21N8A)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qWqPs)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__hbPE
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__arcQh
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vIq4T
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__kEkhs)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__hMGiq)}>
              <div className={classNames(projectcss.all, sty.columns__rvJcU)}>
                <div className={classNames(projectcss.all, sty.column__csNW)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__xSYry)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/stephenPhillipsHostreviewsCoUk3Mhgvrk4TjMUnsplashjpg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__zvwQ)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__d9IE3)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__lldGl
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cdiXy
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames("__wab_instance", sty.button__e8Ah)}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__kNs6W)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column___1J2J)}>
              <div className={classNames(projectcss.all, sty.columns___2BNmy)}>
                <div className={classNames(projectcss.all, sty.column___0Ct0U)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__lNHo)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/neonbrand3GznpblImWcUnsplashjpg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__zBfo5)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__cbdIg)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__qxR22
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___8F7NU
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__l2Up8
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__c0Zpf)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column___39T5D)}>
              <div className={classNames(projectcss.all, sty.columns__mJnMr)}>
                <div className={classNames(projectcss.all, sty.column__iepHg)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___4Hr2)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/neonbrand3GznpblImWcUnsplashjpg.jpeg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__pjNrY)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mSoAq)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4___3FdW
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jlGl
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__vNnhu
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__j8Q79)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Learn more"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__dVxFd)} />
          </p.Stack>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogPost__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogPost__VariantsArgs;
    args?: PlasmicBlogPost__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogPost__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBlogPost__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlogPost__ArgProps,
      internalVariantPropNames: PlasmicBlogPost__VariantProps
    });

    return PlasmicBlogPost__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogPost";
  } else {
    func.displayName = `PlasmicBlogPost.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogPost = Object.assign(
  // Top-level PlasmicBlogPost renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBlogPost
    internalVariantProps: PlasmicBlogPost__VariantProps,
    internalArgProps: PlasmicBlogPost__ArgProps
  }
);

export default PlasmicBlogPost;
/* prettier-ignore-end */
