// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mJU3w7LiKHPBKUALsVD2dj
// Component: GPII4fC9bhF
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: kodhyUpj2vfND/component

import { useScreenVariants as useScreenVariantsohuKUq66Y5Rscr } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ohuKUq66y5rscr/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_mavia_sun.module.css"; // plasmic-import: mJU3w7LiKHPBKUALsVD2dj/projectcss
import sty from "./PlasmicBlogPost.module.css"; // plasmic-import: GPII4fC9bhF/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: ZNnQiOQA-EMqaf/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: CzXEhqLtaA5P__/icon

export type PlasmicBlogPost__VariantMembers = {};

export type PlasmicBlogPost__VariantsArgs = {};
type VariantPropType = keyof PlasmicBlogPost__VariantsArgs;
export const PlasmicBlogPost__VariantProps = new Array<VariantPropType>();

export type PlasmicBlogPost__ArgsType = {};
type ArgPropType = keyof PlasmicBlogPost__ArgsType;
export const PlasmicBlogPost__ArgProps = new Array<ArgPropType>();

export type PlasmicBlogPost__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultBlogPostProps {
  className?: string;
}

function PlasmicBlogPost__RenderFunc(props: {
  variants: PlasmicBlogPost__VariantsArgs;
  args: PlasmicBlogPost__ArgsType;
  overrides: PlasmicBlogPost__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsohuKUq66Y5Rscr()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.column__cJi5A)}>
        <div className={classNames(projectcss.all, sty.freeBox___8PD4F)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.columns__kRyiJ)}
          >
            <div className={classNames(projectcss.all, sty.column__e5O3T)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___4Mdsx
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Twitter"
                  : "Twitter"}
              </h2>

              <div className={classNames(projectcss.all, sty.columns__lZuVn)}>
                <div className={classNames(projectcss.all, sty.column__beixP)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__vbUr)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/_1RpuANoIAgwdy2X3UGeAgjpeg.png",
                      fullWidth: 1280,
                      fullHeight: 720,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__pspLl)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__liTu5)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__omBmV
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w6WqO
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___1XnFd
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___8YPn8
                          )}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.columns__eYdq3)}>
                <div className={classNames(projectcss.all, sty.column__eVXy)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___39ZWt)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/_16CMjpy3P7OsmuEgQrVakwjpeg.png",
                      fullWidth: 1024,
                      fullHeight: 576,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__x3Oi5)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___4CG22)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4___684DJ
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bItzY
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__lEx61
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___4Rjfi
                          )}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.columns__zpHVw)}>
                <div className={classNames(projectcss.all, sty.column__xccjF)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__c3Sy3)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/_1ElxyokWQdHaV6SbgmGygAjpeg.png",
                      fullWidth: 1024,
                      fullHeight: 540,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___8VpyS)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__zv1ZI)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__wruqw
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tasi
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__pHjhr
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__rxS9J)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__nxKv)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__hDlzg
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Medium"
                  : "Medium"}
              </h2>

              <div className={classNames(projectcss.all, sty.columns___5Z9Rm)}>
                <div className={classNames(projectcss.all, sty.column__yhNjU)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bkSxF)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/_1ENwbBn30OuDnORapRRivewpng.png",
                      fullWidth: 1024,
                      fullHeight: 576,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__hXmMo)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xnuTu)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__v0OFa
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7ZhwN
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__gqVev
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__ri3A6)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.columns__lt7Ut)}>
                <div className={classNames(projectcss.all, sty.column__gmZz6)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__eGmBp)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/_1Hun3L2XdnsmrCjVv459Fgjpeg.png",
                      fullWidth: 1400,
                      fullHeight: 787,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__drwem)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__yq7Yv)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__eBeOg
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4SeNn
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__wat8U
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__nqLtE)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.columns__hn6K)}>
                <div className={classNames(projectcss.all, sty.column__pdHs7)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__yMt9X)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/base1Jpg2.jpeg",
                      fullWidth: 500,
                      fullHeight: 327,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__gkcjM)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mVay)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__msRiz
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___4QDe0
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames("__wab_instance", sty.button__udSn)}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__c7Ngp)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__w5Xl4)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__zWdx
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Others"
                  : "Other"}
              </h2>

              <div className={classNames(projectcss.all, sty.columns__fq8D)}>
                <div className={classNames(projectcss.all, sty.column___82Yls)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__o0JlH)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/_1F4P43SsLnMrknYfg9Mqqgjpeg.png",
                      fullWidth: 1280,
                      fullHeight: 675,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__slOp)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xobga)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__gaXnd
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a748
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__axTfI
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg___6Fqh)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.columns__qj3WC)}>
                <div className={classNames(projectcss.all, sty.column__ekxZu)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__xhMwj)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/aboutImg2Png.png",
                      fullWidth: 569,
                      fullHeight: 614,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column___79M7L)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jzHtW)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__zKy2M
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cg9Q3
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__sPslY
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__xtNcz)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>

              <div className={classNames(projectcss.all, sty.columns__r1Cot)}>
                <div className={classNames(projectcss.all, sty.column__k80Un)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__gbMyJ)}
                    displayHeight={"100%" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/mavia_sun/images/istockphoto1149316189612X612Jpg.jpeg",
                      fullWidth: 612,
                      fullHeight: 481,
                      aspectRatio: undefined
                    }}
                  />
                </div>

                <div className={classNames(projectcss.all, sty.column__c3E92)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__kgM4Z)}
                  >
                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__erQdQ
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "Customer Loyalty Programs That Stick"
                        : "Blog heading dummy"}
                    </h4>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oGfcS
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ..."
                      }
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__e3LCv
                      )}
                      color={"blue" as const}
                      endIcon={
                        <ArrowRightsvgIcon
                          className={classNames(projectcss.all, sty.svg__c99Rq)}
                          role={"img"}
                        />
                      }
                      shape={"rounded" as const}
                      showEndIcon={true}
                    >
                      {"Read post"}
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </p.Stack>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicBlogPost__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicBlogPost__VariantsArgs;
    args?: PlasmicBlogPost__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicBlogPost__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicBlogPost__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicBlogPost__ArgProps,
      internalVariantPropNames: PlasmicBlogPost__VariantProps
    });

    return PlasmicBlogPost__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogPost";
  } else {
    func.displayName = `PlasmicBlogPost.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogPost = Object.assign(
  // Top-level PlasmicBlogPost renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicBlogPost
    internalVariantProps: PlasmicBlogPost__VariantProps,
    internalArgProps: PlasmicBlogPost__ArgProps
  }
);

export default PlasmicBlogPost;
/* prettier-ignore-end */
